### ISSUE TITLE
Error using latest release

### ISSUE THREAD

**Issue by nicolo-ribaudo** [thehogfather/brackets-code-folding#131]
All works fine, but I get this error twice:
> Error setting menu item shortcut: 1

**Comment by CarraJack** [comment]
Me too. Same error on the latest release

**Comment by thehogfather** [comment]
@nicolo-ribaudo  @CarraJack what operating system are you running?

**Comment by CarraJack** [comment]
I'm running Windows 8.1

**Comment by nicolo-ribaudo** [comment]
Windows 7

Il giorno gio 23 apr 2015 23:55 CarraJack <notifications@github.com> ha
scritto:

**Comment by nicolo-ribaudo** [comment]
I'm also getting this error using Brackets 1.3 (Using the default code folding extension). Should I report the issue at the Brackets' repo?

**Comment by thehogfather** [comment]
@nicolo-ribaudo If you are using Brackets 1.3, then you can safely uninstall the code folding extension. If you still have the extensions installed then there might be an attempt to register the shortcut keys twice (since code-folding is now integrated into brackets from 1.3). This is the reason for the error message in the console.

**Comment by nicolo-ribaudo** [comment]
@thehogfather Even if I uninstall the extension, I get the error.

**Comment by giacomocarra** [comment]
Installed the latest version of Brackets (1.3) with code-folding integrated on Windows 8.1 and it seems to works fine now. Thanks
